// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/evmos/blob/main/LICENSE)

// @generated by protoc-gen-es v1.9.0
// @generated from file evmos/vesting/v2/events.proto (package evmos.vesting.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * EventCreateClawbackVestingAccount defines the event type
 * for creating a clawback vesting account
 *
 * @generated from message evmos.vesting.v2.EventCreateClawbackVestingAccount
 */
export const EventCreateClawbackVestingAccount = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.EventCreateClawbackVestingAccount",
  () => [
    { no: 1, name: "funder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "vesting_account", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * EventFundVestingAccount defines the event type for funding a vesting account
 *
 * @generated from message evmos.vesting.v2.EventFundVestingAccount
 */
export const EventFundVestingAccount = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.EventFundVestingAccount",
  () => [
    { no: 1, name: "funder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "coins", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "start_time", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "vesting_account", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * EventClawback defines the event type for clawback
 *
 * @generated from message evmos.vesting.v2.EventClawback
 */
export const EventClawback = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.EventClawback",
  () => [
    { no: 1, name: "funder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "account", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "destination", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * EventUpdateVestingFunder defines the event type for updating the vesting funder
 *
 * @generated from message evmos.vesting.v2.EventUpdateVestingFunder
 */
export const EventUpdateVestingFunder = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.EventUpdateVestingFunder",
  () => [
    { no: 1, name: "funder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "account", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "new_funder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

