// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/evmos/blob/main/LICENSE)

// @generated by protoc-gen-es v1.9.0
// @generated from file evmos/vesting/v2/query.proto (package evmos.vesting.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Coin } from "@buf/cosmos_cosmos-sdk.bufbuild_es/cosmos/base/v1beta1/coin_pb.js";

/**
 * QueryBalancesRequest is the request type for the Query/Balances RPC method.
 *
 * @generated from message evmos.vesting.v2.QueryBalancesRequest
 */
export const QueryBalancesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.QueryBalancesRequest",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * QueryBalancesResponse is the response type for the Query/Balances RPC
 * method.
 *
 * @generated from message evmos.vesting.v2.QueryBalancesResponse
 */
export const QueryBalancesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.QueryBalancesResponse",
  () => [
    { no: 1, name: "locked", kind: "message", T: Coin, repeated: true },
    { no: 2, name: "unvested", kind: "message", T: Coin, repeated: true },
    { no: 3, name: "vested", kind: "message", T: Coin, repeated: true },
  ],
);

