// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/evmos/blob/main/LICENSE)

// @generated by protoc-gen-es v1.9.0
// @generated from file evmos/vesting/v2/tx.proto (package evmos.vesting.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";
import { Period } from "@buf/cosmos_cosmos-sdk.bufbuild_es/cosmos/vesting/v1beta1/vesting_pb.js";
import { Coin } from "@buf/cosmos_cosmos-sdk.bufbuild_es/cosmos/base/v1beta1/coin_pb.js";

/**
 * MsgCreateClawbackVestingAccount defines a message that enables creating a
 * ClawbackVestingAccount.
 *
 * @generated from message evmos.vesting.v2.MsgCreateClawbackVestingAccount
 */
export const MsgCreateClawbackVestingAccount = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.MsgCreateClawbackVestingAccount",
  () => [
    { no: 1, name: "funder_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "vesting_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "enable_gov_clawback", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * MsgCreateClawbackVestingAccountResponse defines the
 * MsgCreateClawbackVestingAccount response type.
 *
 * @generated from message evmos.vesting.v2.MsgCreateClawbackVestingAccountResponse
 */
export const MsgCreateClawbackVestingAccountResponse = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.MsgCreateClawbackVestingAccountResponse",
  [],
);

/**
 * MsgFundVestingAccount defines a message that enables funding an existing clawback
 * vesting account.
 *
 * @generated from message evmos.vesting.v2.MsgFundVestingAccount
 */
export const MsgFundVestingAccount = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.MsgFundVestingAccount",
  () => [
    { no: 1, name: "funder_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "vesting_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "start_time", kind: "message", T: Timestamp },
    { no: 4, name: "lockup_periods", kind: "message", T: Period, repeated: true },
    { no: 5, name: "vesting_periods", kind: "message", T: Period, repeated: true },
  ],
);

/**
 * MsgFundVestingAccountResponse defines the
 * MsgFundVestingAccount response type.
 *
 * @generated from message evmos.vesting.v2.MsgFundVestingAccountResponse
 */
export const MsgFundVestingAccountResponse = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.MsgFundVestingAccountResponse",
  [],
);

/**
 * MsgClawback defines a message that removes unvested tokens from a
 * ClawbackVestingAccount.
 *
 * @generated from message evmos.vesting.v2.MsgClawback
 */
export const MsgClawback = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.MsgClawback",
  () => [
    { no: 1, name: "funder_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "account_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "dest_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgClawbackResponse defines the MsgClawback response type.
 *
 * @generated from message evmos.vesting.v2.MsgClawbackResponse
 */
export const MsgClawbackResponse = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.MsgClawbackResponse",
  () => [
    { no: 1, name: "coins", kind: "message", T: Coin, repeated: true },
  ],
);

/**
 * MsgUpdateVestingFunder defines a message that updates the funder account of a
 * ClawbackVestingAccount.
 *
 * @generated from message evmos.vesting.v2.MsgUpdateVestingFunder
 */
export const MsgUpdateVestingFunder = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.MsgUpdateVestingFunder",
  () => [
    { no: 1, name: "funder_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "new_funder_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "vesting_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgUpdateVestingFunderResponse defines the MsgUpdateVestingFunder response
 * type.
 *
 * @generated from message evmos.vesting.v2.MsgUpdateVestingFunderResponse
 */
export const MsgUpdateVestingFunderResponse = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.MsgUpdateVestingFunderResponse",
  [],
);

/**
 * MsgConvertVestingAccount defines a message that enables converting a vesting account to an eth account
 *
 * @generated from message evmos.vesting.v2.MsgConvertVestingAccount
 */
export const MsgConvertVestingAccount = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.MsgConvertVestingAccount",
  () => [
    { no: 1, name: "vesting_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgConvertVestingAccountResponse defines the MsgConvertVestingAccount response type.
 *
 * @generated from message evmos.vesting.v2.MsgConvertVestingAccountResponse
 */
export const MsgConvertVestingAccountResponse = /*@__PURE__*/ proto3.makeMessageType(
  "evmos.vesting.v2.MsgConvertVestingAccountResponse",
  [],
);

