// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/evmos/blob/main/LICENSE)

// @generated by protoc-gen-es v1.9.0
// @generated from file evmos/vesting/v2/vesting.proto (package evmos.vesting.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { BaseVestingAccount, Period } from "@buf/cosmos_cosmos-sdk.bufbuild_es/cosmos/vesting/v1beta1/vesting_pb.js";

/**
 * ClawbackVestingAccount implements the VestingAccount interface. It provides
 * an account that can hold contributions subject to "lockup" (like a
 * PeriodicVestingAccount), or vesting which is subject to clawback
 * of unvested tokens, or a combination (tokens vest, but are still locked).
 *
 * @generated from message evmos.vesting.v2.ClawbackVestingAccount
 */
export declare class ClawbackVestingAccount extends Message<ClawbackVestingAccount> {
  /**
   * base_vesting_account implements the VestingAccount interface. It contains
   * all the necessary fields needed for any vesting account implementation
   *
   * @generated from field: cosmos.vesting.v1beta1.BaseVestingAccount base_vesting_account = 1;
   */
  baseVestingAccount?: BaseVestingAccount;

  /**
   * funder_address specifies the account which can perform clawback
   *
   * @generated from field: string funder_address = 2;
   */
  funderAddress: string;

  /**
   * start_time defines the time at which the vesting period begins
   *
   * @generated from field: google.protobuf.Timestamp start_time = 3;
   */
  startTime?: Timestamp;

  /**
   * lockup_periods defines the unlocking schedule relative to the start_time
   *
   * @generated from field: repeated cosmos.vesting.v1beta1.Period lockup_periods = 4;
   */
  lockupPeriods: Period[];

  /**
   * vesting_periods defines the vesting schedule relative to the start_time
   *
   * @generated from field: repeated cosmos.vesting.v1beta1.Period vesting_periods = 5;
   */
  vestingPeriods: Period[];

  constructor(data?: PartialMessage<ClawbackVestingAccount>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "evmos.vesting.v2.ClawbackVestingAccount";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClawbackVestingAccount;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClawbackVestingAccount;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClawbackVestingAccount;

  static equals(a: ClawbackVestingAccount | PlainMessage<ClawbackVestingAccount> | undefined, b: ClawbackVestingAccount | PlainMessage<ClawbackVestingAccount> | undefined): boolean;
}

/**
 * ClawbackProposal is a gov Content type to clawback funds
 * from a vesting account that has this functionality enabled.
 *
 * @generated from message evmos.vesting.v2.ClawbackProposal
 */
export declare class ClawbackProposal extends Message<ClawbackProposal> {
  /**
   * title of the proposal
   *
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * description of the proposal
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * address is the vesting account address
   * to clawback the funds from
   *
   * @generated from field: string address = 3;
   */
  address: string;

  /**
   * destination_address is the address that will receive
   * the clawbacked funds from the given vesting account. When
   * empty, proposal will return the coins to the vesting
   * account funder.
   *
   * @generated from field: string destination_address = 4;
   */
  destinationAddress: string;

  constructor(data?: PartialMessage<ClawbackProposal>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "evmos.vesting.v2.ClawbackProposal";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClawbackProposal;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClawbackProposal;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClawbackProposal;

  static equals(a: ClawbackProposal | PlainMessage<ClawbackProposal> | undefined, b: ClawbackProposal | PlainMessage<ClawbackProposal> | undefined): boolean;
}

