/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    ChainContent: typeof import('./src/components/ChainContent.vue')['default']
    copy: typeof import('./src/components/validator/ValidatorComissionSheet copy.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValidatorAddressesSheet: typeof import('./src/components/validator/ValidatorAddressesSheet.vue')['default']
    ValidatorAdresesSheet: typeof import('./src/components/validator/ValidatorAdresesSheet.vue')['default']
    ValidatorAdressesSheer: typeof import('./src/components/validator/ValidatorAdressesSheer.vue')['default']
    ValidatorAdressesSheet: typeof import('./src/components/validator/ValidatorAdressesSheet.vue')['default']
    ValidatorBondingSheet: typeof import('./src/components/validator/ValidatorBondingSheet.vue')['default']
    ValidatorComissionSheet: typeof import('./src/components/validator/ValidatorComissionSheet.vue')['default']
    ValidatorInfoSheet: typeof import('./src/components/validator/ValidatorInfoSheet.vue')['default']
    ValidatorInfoSheet_: typeof import('./src/components/ValidatorInfoSheet_.vue')['default']
    ValidatorStakingCommissionChart: typeof import('./src/components/charts/ValidatorStakingCommissionChart.vue')['default']
  }
}
